-- MySQL Script generated by MySQL Workbench
-- Sat Feb  5 01:17:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookdb` DEFAULT CHARACTER SET utf8 ;
USE `bookdb` ;

-- -----------------------------------------------------
-- Table `bookdb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookdb`.`USER` (
  `USERID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(100) NOT NULL,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USERID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookdb`.`PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookdb`.`PRODUCT` (
  `IDPRODUCT` INT NOT NULL AUTO_INCREMENT,
  `USERID` INT NOT NULL,
  `BOOK_NAME` VARCHAR(50) NOT NULL,
  `BOOK_DES` VARCHAR(100) NOT NULL,
  `BOOK_AUTHOR` VARCHAR(20) NOT NULL,
  `PRICE` FLOAT NOT NULL,
  `QUANTITY` INT NOT NULL,
  `BOOK_GENRE` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`IDPRODUCT`),
  INDEX `USERID_idx` (`USERID` ASC),
  CONSTRAINT `USERID`
    FOREIGN KEY (`USERID`)
    REFERENCES `bookdb`.`USER` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
